# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

    trigger:
    - main
    
    pool:
      name: default
    
    variables:
    - group: edumatch_keys
    
    steps:
    # Step 1: Clone the repository
    - script: |
        echo "Fetching the repository..."
        cd /home/aliak30/app
        git pull
      displayName: 'Clone repository'

    # Step 2: Install dependencies
    - script: |
        echo "Installing dependencies..."
        cd /home/aliak30/app
        npm install --production
      displayName: 'Install dependencies'

    # Step 3: Restart the app using PM2
    - script: |
        echo "Restarting the app..."
        cd /home/aliak30/app
        pm2 restart app.js --name "my-app" || pm2 start app.js --name "my-app"
      displayName: 'Restart app with PM2'
